# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"bbc_style": "00_bbplot.ipynb",
         "bbc_style_altair": "00_bbplot.ipynb"}

modules = ["bbplot.py"]

doc_url = "https://noklam.github.io/bbplot/"

git_url = "https://github.com/noklam/bbplot/tree/master/"

def custom_doc_links(name): return None
