# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_bbplot.ipynb (unless otherwise specified).

__all__ = ['bbc_style', 'bbc_style_altair']

# Cell

# plotnine is an implementation of ggplot
import altair as alt
from plotnine import theme, element_text, element_blank, element_line, element_rect


def bbc_style():
    font = "Helvetica"
    bbc_theme = theme(
        plot_title=element_text(family=font,
                                size=22,
                                weight="bold",
                                color="#222222",
                                ha='center',
                                va='top'),
        #       plot_subtitle=element_text(family=font,
        #                                  size=22, plot_margin=(9, 0, 9, 0)), plot_caption=element_blank(),
        legend_position="top",
        legend_title_align=0,
        legend_background=element_blank(),
        legend_title=element_blank(),
        legend_key=element_blank(),
        legend_text=element_text(family=font, size=14, color="#222222"),
        axis_title=element_blank(),
        axis_text=element_text(family=font, size=14, color="#222222"),
        axis_text_x=element_text(margin={
            't': 5,
            'b': 10
        }),
        axis_ticks=element_blank(),
        axis_line=element_blank(),
        panel_grid_minor=element_blank(),
        panel_grid_major_y=element_line(color="#cbcbcb"),
        panel_grid_major_x=element_blank(),
        panel_background=element_blank(),
        strip_background=element_rect(fill="white"),
        strip_text=element_text(size=22, hjust=0))
    return bbc_theme

def bbc_style_altair():
    pass
